config/routes.rb
require 'resque_web'

Cuicui::Application.routes.draw do
  default_url_options host: ENV['DOMAIN']

  scope '(:locale)', locale: /en|fr/ do
    as :user do
      patch '/user/confirmation' => 'confirmations#update',
            via: :patch, as: :update_user_confirmation
    end
    devise_for :users, controllers: {
      sessions: :sessions,
      registrations: :registrations,
      passwords: :passwords,
      confirmations: :confirmations
    }
    resources :users, only: [:show]

    # authenticated :user, lambda {|u| u.role == "admin"} do
    ResqueWeb::Engine.eager_load! if Rails.env.development?
    authenticated :user do
      mount ResqueWeb::Engine => '/resque'
    end

    get '/', to: 'pages#show',
             as: 'home_root',
             id: 'home',
             constraints: { host: "www.#{ENV['DOMAIN']}" }
    get '/pages/*id' => 'pages#show', as: :page, format: false
    root 'sections#show'

    resources :sites do
      resources :sections do
        member do
          get :preview
          get :next
        end
        resources :images do
          collection do
            get :add # Amazon S3 hack.
            get :create # Hack for cloudinary !!
          end
        end
      end
    end

    devise_scope :user do
      get '/admin', to: 'sessions#new'
    end

    get '/robots.txt', to: 'sites#robots', defaults: { format: :txt }
    get ':type.appcache', to: 'manifest#show', defaults: { format: :text }
    get '/sitemap.xml', to: 'sites#sitemap',
                        as: :sitemap,
                        defaults: { format: :xml }
    get 'favicon*all', to: 'favicons#show'
    get 'apple-touch-icon*all', to: 'favicons#show'
    get '/sections', to: 'sections#index'
    get '/:id', to: 'sections#show', as: :s_section
    get '/:section_id/:id', to: 'images#show', as: :s_image
  end
end

app/models/section.rb
# Section
class Section < ActiveRecord::Base
  scope :not_empty, -> { joins(:images).distinct }

  validates :name, presence: true,
                   length: { in: 3..30 },
                   uniqueness: { case_sensitive: false, scope: :site }
  validates :theme, inclusion: { in: %w(light dark) }
  belongs_to :site, touch: true
  has_one :user, through: :site

  has_many :images, -> { order('position') }, dependent: :destroy
  after_save :favicon_changed?, on: :update
  acts_as_list scope: :site

  extend FriendlyId
  friendly_id :slug_candidates,
              use: [:slugged, :finders, :history, :scoped],
              scope: :site

  after_validation :move_friendly_id_error_to_name
  def move_friendly_id_error_to_name
    errors.add(:name,
               *errors.delete(:friendly_id)
              ) if errors[:friendly_id].present?
  end

  def should_generate_new_friendly_id?
    name_changed?
  end

  def description_rendered
    md = Redcarpet::Markdown.new(
      Redcarpet::Render::HTML,
      autolink: true,
      space_after_headers: true
    )
    md.render(description || '')
  end

  def self.reindex
    Site.all.each do |site|
      i = 1
      site.sections.each do |section|
        section.update(position: i)
        i += 1
      end
    end
  end

  def json_import(json)
    %w( name description position description_html theme ).each do |field|
      value = json[field.to_s]
      self[field] = value if value
    end
  end

  def favicon_changed?
    Resque.enqueue(FaviconGeneration, site.id) if first? && position_changed?
  end

  private

  def slug_candidates
    [
      :name,
      [:name, I18n.l(Date.today)],
      [:name, I18n.l(Time.zone.now)]
    ]
  end
end

app/controllers/sections_controller.rb
# SectionsController
class SectionsController < ApplicationController
  before_action :load_site_from_host, only: [:show, :first, :index]
  load_and_authorize_resource :site

  before_action :autoload_if_no_ids, only: [:show]
  before_action :load_section, only: [:show, :edit]
  before_action :redirect_if_section_slug_changed, only: [:show, :edit]
  load_and_authorize_resource through: :site
  before_action :init_image, only: [:edit, :update]

  def autoload_if_no_ids
    @section = @site.sections.first if params[:id].blank?
  end

  def load_section
    @section = @site.sections.friendly.find(params[:id]) if params[:id]
  end

  def redirect_if_section_slug_changed
    redirect_to id: @section if params[:id] && @section.slug != params[:id]
  end

  def index
    @sections = @site.sections.not_empty
    @sections_count = @sections.count
    return redirect_to root_path if @sections_count < 2
  end

  def show
    @image = @section.images.first if @section.images.first
  end

  def preview
    render layout: 'admin'
  end

  def next
  end

  def edit
    render layout: 'admin'
  end

  def new
    @section = @site.sections.build
    render layout: 'admin'
  end

  def create
    @section = @site.sections.build section_params
    if @section.save
      analytics_track('Created Section',
                      id: @section.id,
                      name: @section.name,
                      site: @site.id)
      return redirect_to edit_section_path(@section)
    else
      return render :new, layout: 'admin'
    end
  end

  def destroy
    @section.update site: nil
    Resque.enqueue ObjectDeletion, 'Section', @section.id
    redirect_to edit_site_path(id: @site)
  end

  def update
    previous_position = @section.position
    if @section.update(section_params)
      flash[:success] = t('.success')
      if @section.position != previous_position
        redirect_to my_edit_site_path(@site)
      else
        redirect_to edit_section_path(@section)
      end
    else
      render :edit, layout: 'admin'
    end
  end

  def init_image
    @image = Image.new section: @section
    @image.original.success_action_redirect = add_images_url(@section)
  end

  def section_params
    params.require(:section).permit(:name,
                                    :position,
                                    :description,
                                    :description_html,
                                    :theme)
  end
end

app/views/sections/_image.html.slim
li
  .image
    = my_image_tag image
    = link_to edit_site_section_image_path(id: image, section_id: image.section, site_id: image.site) do
      p.btn.btn-primary
        span.fa.fa-wrench
        = t '.edit'
    = simple_form_for image, method: :delete, html: { class: 'control delete' } do |f|
      = f.submit 'x', class: 'btn btn-danger btn-link'
    - unless image.first?
      = simple_form_for image, method: :put, html: { class: 'control previous' } do |f|
        = f.input :position, as: :hidden, input_html: { value: image.position-1, class: 'position' }
        = f.submit '<', class: 'btn btn-link btn-primary'
    - unless image.last?
      = simple_form_for image, method: :put, html: { class: 'control next' } do |f|
        = f.input :position, as: :hidden, input_html: { value: image.position+1, class: 'position' }
        = f.submit '>', class: 'btn btn-link btn-primary'
    .handle.control
      span.fa.fa-arrows

app/views/sections/_preview.html.haml
.screen{class: defined?(style) ? style : ''}
  .preview-disabled= t('.no-preview', default: 'Javascript must be enabled to see the preview')
  .iframe-preview
    %iframe{ src: url, 'data-size' => (defined?(size) ? size : '1920x1080') }
    .content-drag{style: (drag_style if defined?(drag_style))}
    .background-drag

app/views/sections/edit.html.slim
- breadcrumb @section
.col-md-9.col-md-push-3
  h1
    = t '.images'
    small= t('.images_description')
  .alert.alert-success
    p= t '.add_image'
    = render 'images/form', image: @image
  ul.images.sortable
    = render partial: 'image', collection: @section.images, as: :image
.col-md-3.col-md-pull-9
  h1= t('.edit_section')
  = simple_form_for @section, html: {class: 'edit_section warn-on-exit'} do |f|
    = f.input :name
    = f.submit class: 'btn', data: { 'disable-with'=> t('loading') }

app/views/sections/index.html.haml
- content_for :section_title, "#{@site.title} #{@sections.map(&:name).join(' ')}"
.col-xs-12.preloadable.scrollhistory{ id: "main-nav", data: { url: sections_path, title: title } }
  - x = Math.sqrt(@sections_count).ceil
  - y = (@sections_count.to_f / x.to_f).ceil
  - x,y = [y,x]
  - @sections.each_slice(x).with_index do |sections, index|
    - percent = (1/y.to_f*100).round
    - if index+1 == y
      - percent = 101 - index * percent
    .sections-row{style: ("height: #{percent}%")}
      - sections.each do |section|
        .section
          .wrapper
            = link_to s_section_path(id: section) do
              %h2= section.name
            = my_image_tag section.images.first, :full, alt: section.name, title: section.name

app/views/sections/new.html.haml
- breadcrumb @section
.col-sm-4.col-md-offset-4
  %h1= t('.title')
  = simple_form_for @section, url: site_sections_path(site_id: @section.site) do |f|
    = f.input :name, input_html: { autofocus: :autofocus }, label: false
    = f.submit class: 'btn new-section-submit', data: { 'disable-with'=> t('loading') }

app/views/sections/next.html.haml
- content_for :nav do
  = render 'layouts/nav', site: @site
.image.next-section.col-md-12.col-fullscreen{id: "next-section-#{@section.id}", 'data-url'=> next_section_path(@section), 'data-title' => 'asdadasd'}
  - if @section.images.last
    = link_to_image(@section.images.last, class: 'previous') do
      back
  .content
    %h1= @section.site.title
    %ul.next-section-nav
      - @section.site.sections.each do |section|
        %li{ class: (:active if section == @section) }
          - if section.images.count > 0
            = link_to section_path(section) do
              = image_tag section.images.first.url(:thumbnail), alt: section.name, title: section.name, class: 'img-responsive', size: '250x200'
              .section-name= section.name

app/views/sections/preview.html.haml
.col-md-12
  = link_to t('.go_back_to_edit'), edit_section_path(@section), class: 'btn btn-primary preview-back'
  = render 'preview', url: section_path(@section)

app/views/sections/show.html.haml
- content_for :nav do
  = render 'layouts/nav', site: @site
- if @image
  = render @image
- else
  .col-md-12
    %h1 Oups, this section is empty...