config/routes.rb
require 'resque_web'

Cuicui::Application.routes.draw do
  default_url_options host: ENV['DOMAIN']

  scope '(:locale)', locale: /en|fr/ do
    as :user do
      patch '/user/confirmation' => 'confirmations#update',
            via: :patch, as: :update_user_confirmation
    end
    devise_for :users, controllers: {
      sessions: :sessions,
      registrations: :registrations,
      passwords: :passwords,
      confirmations: :confirmations
    }
    resources :users, only: [:show]

    # authenticated :user, lambda {|u| u.role == "admin"} do
    ResqueWeb::Engine.eager_load! if Rails.env.development?
    authenticated :user do
      mount ResqueWeb::Engine => '/resque'
    end

    get '/', to: 'pages#show',
             as: 'home_root',
             id: 'home',
             constraints: { host: "www.#{ENV['DOMAIN']}" }
    get '/pages/*id' => 'pages#show', as: :page, format: false
    root 'sections#show'

    resources :sites do
      resources :sections do
        member do
          get :preview
          get :next
        end
        resources :images do
          collection do
            get :add # Amazon S3 hack.
            get :create # Hack for cloudinary !!
          end
        end
      end
    end

    devise_scope :user do
      get '/admin', to: 'sessions#new'
    end

    get '/robots.txt', to: 'sites#robots', defaults: { format: :txt }
    get ':type.appcache', to: 'manifest#show', defaults: { format: :text }
    get '/sitemap.xml', to: 'sites#sitemap',
                        as: :sitemap,
                        defaults: { format: :xml }
    get 'favicon*all', to: 'favicons#show'
    get 'apple-touch-icon*all', to: 'favicons#show'
    get '/sections', to: 'sections#index'
    get '/:id', to: 'sections#show', as: :s_section
    get '/:section_id/:id', to: 'images#show', as: :s_image
  end
end

app/models/site.rb
# Site
class Site < ActiveRecord::Base
  belongs_to :user
  has_many :sections, -> { order('position') }, dependent: :destroy
  has_many :images, through: :sections

  LANGUAGES = LanguageList::COMMON_LANGUAGES.map(&:iso_639_1)
  validates :language, inclusion: LANGUAGES
  validates_with FontFamilyValidator,
                 fields: [:font_header, :font_body],
                 allow_nil: true
  validates :title, presence: true,
                    length: { in: 3..30 },
                    uniqueness: { case_sensitive: false }

  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders, :history]

  mount_uploader :favicon, FaviconUploader

  def should_generate_new_friendly_id?
    title_changed?
  end

  def self.import(user, url)
    site = json_import(JSON.parse(HTTParty.get(url).body))
    site.user = user
    site.save
  end

  def favicon_process
    return unless sections.first && sections.first.images.first
    LocalFile.process(sections.first.images.first.url(:full)) do |file|
      self.favicon = file
      save!
    end
  end

  def self.json_import(json)
    site = Site.new
    site.json_import(json)
    site.save!
    json['sections'].each do |json_section|
      section = site.sections.new
      section.json_import(json_section)
      section.save!
      json_section['images'].each do |json_image|
        image = section.images.new
        image.json_import(json_image)
        image.save!
      end
    end
    site
  end

  def self.find_by_host(host)
    custom_site = find_by_domain(host)
    return custom_site if custom_site
    match = Regexp.new("^(.*)\.#{ENV['DOMAIN']}$").match(host)
    return find(match[1]) if match
  rescue ActiveRecord::RecordNotFound
    nil
  end

  def host
    if domain.present?
      domain
    else
      "#{slug}.#{ENV['DOMAIN']}"
    end
  end

  def json_import(json)
    %w( title description css metas language twitter_id facebook_id
        facebook_app_id google_plus_id google_analytics_id).each do |field|
      value = json[field.to_s]
      self[field] = value if value
    end
  end
end

app/controllers/sites_controller.rb
# SitesController
class SitesController < ApplicationController
  before_action :load_site_from_host, only: [:show, :sitemap, :robots]
  load_and_authorize_resource

  before_action :authenticate_user!, only: [:index]
  def index
    @sites = current_user.sites
    if @sites.count > 0
      render layout: 'admin'
    else
      redirect_to new_site_path
    end
  end

  def new
    render layout: 'admin'
  end

  def create
    @site.user = current_user
    if @site.save
      analytics_track('Created Site', id: @site.id, name: @site.title)
      @section = @site.sections.create(name: t('sites.create.first_section'))
      redirect_to edit_site_section_path(site_id: @site, id: @section)
    else
      render :new, layout: 'admin'
    end
  end

  def show
    @site = Site.find(params[:id])
    respond_to do |format|
      format.html
      format.json do
        return render json: @site, include: {
          sections: { include: { images: {} } }
        }
      end
    end
  end

  def edit
    @site = Site.find(params[:id])
    render layout: 'admin'
  end

  def update
    @site = Site.find(params[:id])
    @site.update!(site_params)
    flash[:success] = I18n.t('sites.update.success')
    redirect_to edit_site_path(id: @site)
  end

  def robots
    @allow = true
    render layout: false
  end

  def sitemap
    return render 'sitemap_root',
                  layout: false,
                  formats: [:xml] if request_root?
    @urls = sitemap_urls
    render layout: false, formats: [:xml]
  end

  def request_root?
    request.host == "www.#{ENV['DOMAIN']}"
  end

  def sitemap_urls
    @site.sections.each_with_object([]) do |section, urls|
      section.images.each do |image|
        urls << {
          loc: s_image_url(section_id: section, id: image),
          changefreq: :weekly,
          priority: image.priority
        }
      end
    end
  end

  def destroy
    @site.update user: nil
    Resque.enqueue ObjectDeletion, 'Site', @site.id
    redirect_to user_path(id: current_user)
  end

  def site_params
    params.require(:site).permit(:title, :slug, :description, :css, :metas,
                                 :language, :twitter_id, :facebook_id,
                                 :facebook_app_id, :google_plus_id,
                                 :google_analytics_id, :domain, :font_header,
                                 :font_body)
  end
end

app/views/sites/_navbar.html.haml
%nav.navbar.navbar-fixed-bottom.navbar-inverse{role: 'navigation'}
  .navbar-header
    %button.navbar-toggle{'data-target' => '#nav-content', 'data-toggle' => 'collapse', type: 'button'}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to site.name, root_path, class:'navbar-brand'
  #nav-content.collapse.navbar-collapse
    %ul.nav.navbar-nav
      %li
        = link_to 'Portofolio', 'portofolio.html'
      %li
        = link_to 'publications', 'publications.html'
      %li
        = link_to 'Les photographes', 'photographes.html'
      %li
        = link_to 'Contact', 'mailto:contact@studiocuicui.com'

app/views/sites/_section.html.slim
li
  .section
    = my_image_tag section, :full
    = link_to edit_site_section_path(site_id: site, id: section) do
      p= section.name
    = simple_form_for section, method: :delete, html: { class: 'control delete' } do |f|
      = f.submit 'x', class: 'btn btn-danger btn-link', data: { confirm: t('.delete_confirm') }
    - unless section.first?
      = simple_form_for section, method: :put, html: { class: 'control previous' } do |f|
        = f.input :position, as: :hidden, input_html: { value: section.position-1, class: 'position' }
        = f.submit '<', class: 'btn btn-link btn-primary'
    - unless section.last?
      = simple_form_for section, method: :put, html: { class: 'control next' } do |f|
        = f.input :position, as: :hidden, input_html: { value: section.position+1, class: 'position' }
        = f.submit '>', class: 'btn btn-link btn-primary'
    .handle.control
      span.fa.fa-arrows

app/views/sites/edit.html.haml
- breadcrumb @site
.col-md-9.col-md-push-3
  %h1= t '.sections'
  - if @site.sections.count == 0
    .alert.alert-info
      = t '.no_sections'
  %ul.sections.sortable
    = render partial: 'section', collection: @site.sections, as: :section, locals: { site: @site }
    %li.not-sortable
      .section.new
        = link_to new_site_section_path(site_id: @site), id: 'new_section' do
          .fa.fa-plus
.col-md-3.col-md-pull-9
  .row
    .col-md-12
      %h1= t('.edit_site')
      = simple_form_for @site, url: site_path(id: @site),  html: { class: 'warn-on-exit' } do |f|
        = f.input :title, input_html: {class: 'input-lg'}, label: false
        = f.input :description, as: :text, input_html: { rows: 10 }
        = f.input :language, collection: LanguageList::COMMON_LANGUAGES.map{|l| [l.name, l.iso_639_1]}, prompt: false
        = f.input :font_header, as: :select, collection: Font.families
        = f.input :font_body, as: :select, collection: Font.families
        - if params[:advanced]
          %p
            %span.caret
            = link_to t('.advanced'), url_for(advanced: nil)
          = f.input :domain
          = f.input :twitter_id
          = f.input :facebook_id
          = f.input :facebook_app_id
          = f.input :google_plus_id
          = f.input :google_analytics_id
        - else
          %p
            %span.caret
            = link_to t('.advanced'), url_for(advanced: true)
        .admin-advanced
          = f.input :metas, as: :text, input_html: { rows: 4 }
          = f.input :favicon, as: :file
          .alert.alert-warning
            = t '.warning', default: 'It can take some time before the favicon gets updated...'
          = f.input :css, input_html: { rows: 30}
        = f.submit class: 'btn', data: { 'disable-with'=> t('loading') }
  .row
    .col-md-12
      %h1= t('.delete')
      .alert.alert-danger
        %p= t('.delete_warning')
        = link_to site_path(id: @site), method: :delete,  class: 'btn btn-danger', data: { confirm: t('confirm') } do
          .fa.fa-trash-o
          = t('.delete')

app/views/sites/index.html.haml
- breadcrumb :sites
.col-md-8.col-md-offset-2
  %h1
    = t('.sites')
  %table.table.table-striped
    %thead
      %tr
        %td=t '.name'
        %td=t '.sections'
        %td=t '.images'
        %td=t '.open'
    %tbody
      - @sites.each do |site|
        %tr
          %td
            = link_to edit_site_path(id: site) do
              = site.title
          %td= site.sections.count
          %td= site.images.count
          %td
            = link_to site_url(site), class: 'btn btn-link', target: '_blank' do
              = site_url(site)
              .fa.fa-external-link
  = link_to t('.new'), new_site_path, class: 'btn btn-success'

app/views/sites/new.html.haml
- breadcrumb @site
.col-sm-4.col-md-offset-4
  %h1=t('.title')
  = simple_form_for @site,  html: { class: 'warn-on-exit' } do |f|
    = f.input :title, input_html: { autofocus: true }, label: false
    = f.submit class: 'btn new-site-submit', data: { 'disable-with'=> t('loading') }

app/views/sites/robots.erb
User-Agent: *
<% if @allow %>
Allow: /
<% else %>
Disallow: /
<% end %>

Sitemap: <%= sitemap_url %>

app/views/sites/show.html.haml
.col-md-12
  %h1= @site.title
  .row
    - @site.sections.each do |section|
      .col-md-12
        %h3= section.name
      .col-md-12
        .row
          - section.images.each do |image|
            .col-md-3.col-lg-2.col-xs-4
              = link_to image_path(image) do
                = image_tag image.image.url(:thumbnail), alt: image.legend, title: image.legend, class: 'img-responsive'

app/views/sites/sitemap.xml.haml
!!! XML
%urlset{ xmlns: 'http://www.sitemaps.org/schemas/sitemap/0.9' }
  - @urls.each do |url|
    %url
      %loc= url[:loc]
      %changefreq= url[:changefreq]
      %priority= url[:priority]

app/views/sites/sitemap_root.xml.haml
!!! XML
%urlset{ xmlns: 'http://www.sitemaps.org/schemas/sitemap/0.9', 'xmlns:xhtml' =>'http://www.w3.org/1999/xhtml' }
  - [ :root_url, :new_user_registration_url, :new_user_session_url ].each do |route|
    %url
      %loc= send(route)
      %changefreq weekly
      %priority= route == :root_url ? 1 : 0.5
      - I18n.available_locales.each do |locale|
        %xhtml:link{ rel:"alternate", hreflang: locale, href: send(route, locale: locale) }