config/routes.rb
require 'resque_web'

Cuicui::Application.routes.draw do
  default_url_options host: ENV['DOMAIN']

  scope '(:locale)', locale: /en|fr/ do
    as :user do
      patch '/user/confirmation' => 'confirmations#update',
            via: :patch, as: :update_user_confirmation
    end
    devise_for :users, controllers: {
      sessions: :sessions,
      registrations: :registrations,
      passwords: :passwords,
      confirmations: :confirmations
    }
    resources :users, only: [:show]

    # authenticated :user, lambda {|u| u.role == "admin"} do
    ResqueWeb::Engine.eager_load! if Rails.env.development?
    authenticated :user do
      mount ResqueWeb::Engine => '/resque'
    end

    get '/', to: 'pages#show',
             as: 'home_root',
             id: 'home',
             constraints: { host: "www.#{ENV['DOMAIN']}" }
    get '/pages/*id' => 'pages#show', as: :page, format: false
    root 'sections#show'

    resources :sites do
      resources :sections do
        member do
          get :preview
          get :next
        end
        resources :images do
          collection do
            get :add # Amazon S3 hack.
            get :create # Hack for cloudinary !!
          end
        end
      end
    end

    devise_scope :user do
      get '/admin', to: 'sessions#new'
    end

    get '/robots.txt', to: 'sites#robots', defaults: { format: :txt }
    get ':type.appcache', to: 'manifest#show', defaults: { format: :text }
    get '/sitemap.xml', to: 'sites#sitemap',
                        as: :sitemap,
                        defaults: { format: :xml }
    get 'favicon*all', to: 'favicons#show'
    get 'apple-touch-icon*all', to: 'favicons#show'
    get '/sections', to: 'sections#index'
    get '/:id', to: 'sections#show', as: :s_section
    get '/:section_id/:id', to: 'images#show', as: :s_image
  end
end

app/models/image.rb
# Image
class Image < ActiveRecord::Base
  has_one :site, through: :section
  belongs_to :section, touch: true
  has_one :user, through: :site

  validates :title, length: { maximum: 250 }
  acts_as_list scope: :section
  mount_uploader :cloudinary, CloudinaryUploader

  mount_uploader :original, FileUploader
  mount_uploader :image, ImageUploader
  mount_uploader :snapshot, ImageUploader

  after_save :favicon_changed?, on: [:create, :update]

  def url(version = :original)
    return download_url if version == :original
    return image.url version if image?
    download_url
  end

  def download_url
    return Rails.cache.fetch([self, 'original-url'], expires_in: 1.hour) do
      original.url
    end if original?
    image.url
  end

  def processed?
    image?
  end

  def process
    LocalFile.process(download_url) do |file|
      self.image = file
      save!
    end
  end

  def snapshot!
    # return snapshot.url(version) if snapshot? && [:thumbnail, :icon].include?(version)
    Tempfile.open(['snapshot', '.png'], Rails.root.join('tmp'), encoding: 'ascii-8bit') do |file|
      Phantomjs.run(
        Rails.root.join('lib', 'rasterize.js').to_s,
        Rails.application.routes.url_helpers.site_section_image_url(site_id: site, section_id: section, id: id),
        file.path,
        '1920px*1080px',
        '1'
      )
      self.snapshot = file
      self.save!
    end
  end

  before_save do
    if legend.nil? && defined?(exifs['image_description'])
      self.legend = exifs['image_description']
    end
  end

  def content_rendered
    md = Redcarpet::Markdown.new(
      Redcarpet::Render::HTML,
      autolink: true,
      space_after_headers: true
    )
    md.render(content || '')
  end

  def self.reindex
    Section.all.each do |section|
      i = 1
      section.images.each do |image|
        image.update(position: i)
        i += 1
      end
    end
  end

  def self.cleanup
    Image.find_each { |i| i.destroy if i.section.nil? }
  end

  def priority
    total = section.images.count
    (total - position + 1).to_f / (total).to_f
  end

  def content_text
    return '' unless content?
    Nokogiri::HTML(content_rendered).text
  end

  def content_string
    content_text.gsub("\n", ' ')
  end

  def seo_title
    if title? || content? || legend?
      "#{title} #{content_string} #{legend}"
    else
      section.name
    end
  end

  def seo_description
    return content unless content.blank?
    legend
  end

  def to_param
    if legend
      "#{id}-#{legend.parameterize[0..60]}"
    else
      id.to_s
    end
  end

  def import_from_url(url)
    file = Tempfile.new(['import', '.jpg'],
                        Rails.root.join('tmp'),
                        encoding: 'ascii-8bit')
    begin
      file.write(URI.parse(url).read)
      self.image = file
      self.save!
    ensure
      file.close
      file.unlink
    end
  end

  def json_import(json)
    %w( position legend full content content_css title image_css
        focusx focusy ).each do |field|
      value = json[field.to_s]
      self[field] = value if value
    end
    import_from_url(json['original_url']) if json['original_url']
  end

  def favicon_changed?
    return unless first? && section && section.first?
    Resque.enqueue FaviconGeneration, site.id if focusx_changed? ||
                                                 focusy_changed? ||
                                                 position_changed?
  end

  class << self
    def race_fix
      connection.update(
        "UPDATE images SET position = ranked.rank FROM (#{ranked_sql}) AS ranked WHERE images.id = ranked.id",
        'Image Update'
      )
    end

    def race_test
      select('position').group('position').having('COUNT(position) > 1').any?
    end

    def ranked_sql
      connection.unprepared_statement do
        ranked.to_sql
      end
    end

    def ranked
      select('id, rank() OVER (ORDER BY position, created_at) AS rank')
    end
  end
end

app/controllers/images_controller.rb
# ImageController
class ImagesController < ApplicationController
  before_action :load_site_from_host, only: [:show]

  load_and_authorize_resource :site

  before_action :load_section, only: [:show]
  load_and_authorize_resource :section, through: :site
  before_action :redirect_if_section_slug_changed, only: [:show]

  load_and_authorize_resource through: :section

  def new
    respond_to do |format|
      format.json do
        @image.original.use_action_status = true
        @image.original.success_action_status = '201'
        render json: @image.original.params
      end
    end
  end

  def add
    @image = Image.new(section: @section)
    @uploader = @image.original.key = params[:key]
    @image.save
    flash[:error] = @image.errors.full_messages.to_sentence unless @image.save
    Resque.enqueue ImageConversion, @image.id
    analytics_track('Created Image', id: @image.id, position: @image.position,
                                     section: @section.id, site: @site.id)
    redirect_to edit_section_path(@section)
    @section.images.race_fix if @section.images.race_test
  end

  def create
    return redirect_to edit_section_path(@section),
                       flash: { error: params[:error] } if params[:error]
    @image = @section.images.build
    @image.image = cloudinary_path
    @image.save!
    @image.extract_exifs
    @images = @section.images
    # with cloudinary we need to force the format ;-(
    return render 'create.js' if request.xhr?
    redirect_to edit_section_path(@section)
  end

  def show
    stale?([@site, @section, @image])do
      render 'sections/show'
    end
  end

  def edit
    render layout: 'admin'
  end

  def update
    previous_position = @image.position
    if @image.update(image_params)
      if @image.position != previous_position
        redirect_to edit_section_path(@section)
      else
        redirect_to edit_image_path(@image)
      end
    else
      render :edit, layout: 'admin'
    end
  end

  def destroy
    @image.update section: nil
    Resque.enqueue ObjectDeletion, 'Image', @image.id
    redirect_to edit_section_path @section
  end

  def image_params
    params.require(:image).permit(:legend,
                                  :title,
                                  :full,
                                  :content,
                                  :content_css,
                                  :image_css,
                                  :position,
                                  :focusx,
                                  :focusy)
  end

  private

  def cloudinary_path
    path = "#{params[:resource_type]}/#{params[:type]}"
    path += "/v#{params[:version]}/#{params[:public_id]}"
    path += ".#{params[:format]}" if params[:format].present?
    path += "##{params[:signature]}"
    path
  end
end

app/helpers/images_helper.rb
# ImagesHelper
module ImagesHelper
  def my_image_tag(image, version = :full, options = {})
    return my_image_tag(image.sections.first, version, options) if image.instance_of? Site
    return my_image_tag(image.images.first, version, options) if image.instance_of? Section
    # options[:size] ||= image.geometries[version.to_s] if image.geometries && image.geometries[version.to_s]
    if image
      options[:title] ||= image.seo_title
      options[:alt] ||= image.seo_title
      options[:style] = "background-image: url('#{image.url(:full)}');#{options[:style]}"
      if image.focusx && image.focusy
        options[:style] += "background-position: #{image.focusx}% #{image.focusy}%"
      end
      image_tag image.url(version), options
    else
      image_tag Image.new.url(version), options
    end
  end

  def link_to_image(image, options = {})
    options[:class] ||= ''
    options[:class] += ' scroll'
    options[:'data-scroll'] = "#image-#{image.id}"
    link_to s_image_path(id: image, section_id: image.section), options do
      if block_given?
        yield
      else
        image.title
      end
    end
  end
end

app/views/images/_form.html.haml
= direct_upload_form_for image.original, html: { class: 'fileupload' } do |f|
  .uploading{style: 'display: none'}
    .upload_in_progress
      %h1=t('.upload_in_progress')
      -# = t('.upload_in_progress_link_html', link: edit_section_path(@section), default: '<a href="%{link}" class="btn btn-success" target="_blank">Continue to edit the site</a>')
    .progress
      .progress-bar.active.progress-bar-success.progress-bar-striped
  = f.file_field :original, data: { new_url: new_site_section_image_path(site_id: image.section.site, section_id: image.section), add_url: add_site_section_images_path(site_id: image.section.site, section_id: image.section) }
  = f.submit t('.upload'), data: { 'disable-with'=> t('loading') }

app/views/images/_image.html.haml
.image.col-md-12.col-fullscreen{itemscope: '', itemtype: 'http://schema.org/Photograph', id: "image-#{image.id}", class: ('full' if image.full), 'data-url'=> image_url(image), 'data-title'=>image.seo_title}
  .viewer
    .content
      - unless defined? no_controls
        - unless image.first?
          = link_to page_path(image.page) , class: 'restart btn btn-default' do
            &#8593;
      .image-content{style: "#{'display: none;' unless image.content.present? || image.title.present?} #{image.content_css}"}
        - if image.title.present?
          %h1=image.title
        = image.content_rendered.html_safe
      = my_image_tag image, :full, class: "main-image #{'custom' if image.image_css.present? }", itemprop: 'url', style: image.image_css
      -# = image_tag image.url(:full), alt: image.legend, title: image.legend, class: 'main-image', itemprop: 'url', style: "background-image: url(#{image.url(:full)}); #{image.image_css}"
      .image-description{ style: ('display: none;' unless image.legend.present?) }
        %span{itemprop: 'description'}= image.legend
      - unless defined? no_controls
        - if image.lower_item
          =link_to image_url(image.lower_item) , class: 'scroll control next preload', 'data-scroll'=> "#image-#{image.lower_item.id}" do
            %p next
        - else
          = link_to pages_path, class: 'scroll control next' do
            %p next
        - if image.higher_item
          =link_to image_url(image.higher_item) , class: 'scroll control previous', 'data-scroll'=> "#image-#{image.higher_item.id}" do
            %p previous
        - else
          =link_to pages_path, class: 'scroll control previous' do
            %p previous

        -# if image.last? and image.page.images.count > 1
          =link_to s_image_path(page_id: image.page, id: image.page.images.first) , class: 'control restart', 'data-scroll'=> "#image-#{image.page.images.first}" do
            %p Back to first image
        -# if image.higher_items.first
          =link_to s_image_path(page_id: image.page, id: image.higher_items.first) , class: 'control first preload' do
            %p= '<<'
  -# if image.last?
    .last-image-menu
      = link_to '', site_pages_path(site_id: image.site), class: 'index'
      %ul.nav.nav-pills.nav-stacked
        - image.page.site.pages.each do |page|
          %li{class: ('active' if page == image.page)}
            = link_to page.name, s_page_path(page)

  -#.image-progress
    -#%span.position=@image.position
    -#%span.sep /
    -#%span.total=@image.page.images.count
-content_for :page_title, image.seo_title
-content_for :head do
  - description = image.seo_description
  - image_url = image.url(:social)
  %meta{property: 'og:title', content: title}
  %meta{property: 'og:image', content: image_url}
  %meta{property: 'og:description', content: description}
  %meta{property: 'og:url', content: s_image_url(page_id: image.page, id: image)}
  %meta{property: 'og:site_name', content: image.page.site.title}
  %meta{property: 'og:see_also', content: root_url}
  %meta{property: 'og:type', content: 'article'}
  - facebook_app = ''
  - facebook_admin = ''
  - unless image.site.facebook_app_id.blank?
    %meta{property: 'og:app_id', content: image.site.facebook_app_id}
  - unless image.site.facebook_id.blank?
    %meta{property: 'fb:admins', content: image.site.facebook_id}

  %meta{property: 'twitter:card', content: 'photo'}
  %meta{property: 'twitter:title', content: title}
  %meta{property: 'twitter:image:src', content: image_url}
  - twitter_id = image.site.twitter_id
  - if twitter_id
    %meta{property: 'twitter:site', content: twitter_id}
    %meta{property: 'twitter:creator', content: twitter_id}

  - google_id= image.site.google_plus_id
  - unless google_id.blank?
    %link{rel: 'author', href: "https://plus.google.com/#{google_id}/posts"}
    %link{rel: 'publisher', href: "https://plus.google.com/#{google_id}"}

  -# <html itemscope itemtype="http://schema.org/Article">
  %meta{property: 'description', content: description}
  %meta{property: 'name', content: title}
  %meta{property: 'image', content: image_url}

app/views/images/_image.html.slim
.viewer-controls.preloadable id="viewer-image-#{image.id}"
  - if image.higher_item
    = link_to image_url(image.higher_item), class: 'btn btn-default previous' do
      span.fa.fa-angle-left
  - else
    - if @site.sections.not_empty.count > 1
      = link_to sections_path, class: 'btn btn-default previous home' do
        span.fa.fa-angle-left

  = render 'images/viewer', image: image

  - if image.lower_item
    = link_to image_url(image.lower_item), class: 'btn btn-default next preload' do
      span.fa.fa-angle-right
    .help-scroll-icon
      span.fa.fa-angle-double-down
  - else
    = link_to page_path(id: 'legal'), class: 'legal' do
      span.fa.fa-info-circle
    - if @site.sections.not_empty.count > 1
      = link_to sections_path , class: 'btn btn-default next preload' do
        span.fa.fa-angle-right
      .help-scroll-icon
        span.fa.fa-angle-double-down

- content_for :page_title, "#{@site.title} #{image.seo_title}"
- content_for :head do
  - description = image.seo_title
  - image_url = image.url(:social)
  - url = s_image_url(section_id: image.section, id: image)
  meta property='og:title' content=title
  meta property='og:image' content=image_url
  meta property='og:description' content=description
  meta property='og:url' content=url
  meta property='og:site_name' content=image.section.site.title
  meta property='og:see_also' content=root_url
  meta property='og:type' content='article'
  - facebook_app = ''
  - facebook_admin = ''
  - if image.site.facebook_app_id?
    meta property='og:app_id' content=image.site.facebook_app_id
  - if image.site.facebook_id?
    meta property='fb:admins' content=image.site.facebook_id
  meta property='twitter:card' content='photo'
  meta property='twitter:title' content=title.truncate(60)
  meta property='twitter:description' content=title
  meta property='twitter:image' content=image_url
  meta property='twitter:url' content=url
  - twitter_id = image.site.twitter_id
  - if twitter_id.present?
    meta property='twitter:site' content=twitter_id
    meta property='twitter:creator' content=twitter_id
  - google_id= image.site.google_plus_id
  - unless google_id.blank?
    link rel='author' href="https://plus.google.com/#{google_id}/posts"
    link rel='publisher' href="https://plus.google.com/#{google_id}"
  -# <html itemscope itemtype="http://schema.org/Article">
  meta property='description' content=description
  meta property='name' content=title
  meta property='image' content=image_url

app/views/images/_image_edit.html.haml
%li.image
  .handle.control
    %span.fa.fa-arrows
  =link_to edit_image_path(image) do
    =image_tag image.url(:thumbnail), title: image.legend, size: '250x200', style: "background-image: url(#{image.url(:thumbnail)})", class: ('processing' unless image.processed?)
  =link_to edit_image_path(image), class: 'control edit' do
    %span.fa.fa-gears
    = t('.edit')
  = simple_form_for image, method: :delete, html: { class: 'control delete' } do |f|
    = f.submit 'x', class: 'btn btn-danger btn-link'
  - unless image.first?
    = simple_form_for image, method: :put, html: { class: 'control previous' } do |f|
      = f.input :position, as: :hidden, input_html: { value: image.position-1, class: 'position'}
      = f.submit '<', class: 'btn btn-link btn-primary'
  - unless image.last?
    = simple_form_for image, method: :put, html: { class: 'control next' } do |f|
      = f.input :position, as: :hidden, input_html: { value: image.position+1, class: 'position' }
      = f.submit '>', class: 'btn btn-link btn-primary'

app/views/images/_viewer.html.slim
.image-viewer.scrollhistory itemscope= '' itemtype='http://schema.org/Photograph' id="image-#{image.id}" data-url=image_url(image) data-title=image.seo_title
  .content
    - if image.content? || image.title?
      .image-content style=image.content_css
        - if image.title?
          h1= image.title
        = image.content_rendered.html_safe
    - else
      .image-content style='display: none;'
    = my_image_tag image, :full, class: "image #{'custom' if image.image_css.present? } #{'full' if image.full }", itemprop: 'url', style: image.image_css
    - if image.legend?
      .image-description
        span itemprop='description' = image.legend
    - else
      .image-description style='display: none;'

app/views/images/edit.html.haml
- breadcrumb @image
= simple_form_for @image, html: { class: 'warn-on-exit' } do |f|
  .col-md-12
    .row
      .col-md-4#previews
        %h2= t '.full'
        = f.input :full, wrapper: :vertical_boolean
        %h2= t '.focus'
        .alert.alert-info.help
          = t '.focuspoint.content'
        #focuspoint
          .selector
            = my_image_tag @image, :full, class: 'image'
            .pointer{style: "top: #{@image.focusy || 50}%; left: #{@image.focusx || 50}%"}
              .handle
          .previews
            .wrapper
              = my_image_tag @image, :full, class: 'preview one'
              = my_image_tag @image, :full, class: 'preview two'
        = f.input :content_css
        = f.input :focusx
        = f.input :focusy

        = f.input :image_css
        %h2= t '.text'
        = f.input :title, label: false, input_html: { class: 'input-lg' }
        .form-group.text.optional.section_description
          -# %label.text.optional.control-label{for: 'image_content'} Content
          .controls
            .wmd-panel
              #wmd-button-bar
              %textarea.text.optional.form-control#wmd-input{name: 'image[content]', rows: '5', placeholder: t('simple_form.placeholders.defaults.content')}= f.object.content
              #wmd-preview.wmd-panel.wmd-preview= f.object.content_rendered.html_safe
        = f.input :legend, label: false, input_html: {value: f.object.legend }
        = f.submit class: 'btn hidden-md', data: { 'disable-with'=> t('loading') }
      .col-md-8#previews
        .row
          .col-md-11
            %h3= t('.desktop')
            =render 'sections/preview', url: preview_image_path(@image), drag_style: @image.content_css, size: '1920x1080', style: 'desktop'
          .col-md-5
            %h3= t('.laptop')
            =render 'sections/preview', url: preview_image_path(@image), drag_style: @image.content_css, size: '1366x768', style: 'laptop'
          .col-md-4
            %h3= t('.tablet')
            =render 'sections/preview', url: preview_image_path(@image), drag_style: @image.content_css, size: '1010x660', style: 'tablet'
          .col-md-2
            %h3= t('.phone')
            =render 'sections/preview', url: preview_image_path(@image), drag_style: @image.content_css, size: '640x1136', style: 'phone'
    .row
      .col-md-12
        = f.submit class: 'btn hidden-lg', data: { 'disable-with'=> t('loading') }

app/views/images/show.html.haml
- content_for :nav do
  = render 'layouts/nav', site: @site
= render @image