config/routes.rb
require 'resque_web'

Cuicui::Application.routes.draw do
  default_url_options host: ENV['DOMAIN']

  scope '(:locale)', locale: /en|fr/ do
    as :user do
      patch '/user/confirmation' => 'confirmations#update',
            via: :patch, as: :update_user_confirmation
    end
    devise_for :users, controllers: {
      sessions: :sessions,
      registrations: :registrations,
      passwords: :passwords,
      confirmations: :confirmations
    }
    resources :users, only: [:show]

    # authenticated :user, lambda {|u| u.role == "admin"} do
    ResqueWeb::Engine.eager_load! if Rails.env.development?
    authenticated :user do
      mount ResqueWeb::Engine => '/resque'
    end

    get '/', to: 'pages#show',
             as: 'home_root',
             id: 'home',
             constraints: { host: "www.#{ENV['DOMAIN']}" }
    get '/pages/*id' => 'pages#show', as: :page, format: false
    root 'sections#show'

    resources :sites do
      resources :sections do
        member do
          get :preview
          get :next
        end
        resources :images do
          collection do
            get :add # Amazon S3 hack.
            get :create # Hack for cloudinary !!
          end
        end
      end
    end

    devise_scope :user do
      get '/admin', to: 'sessions#new'
    end

    get '/robots.txt', to: 'sites#robots', defaults: { format: :txt }
    get ':type.appcache', to: 'manifest#show', defaults: { format: :text }
    get '/sitemap.xml', to: 'sites#sitemap',
                        as: :sitemap,
                        defaults: { format: :xml }
    get 'favicon*all', to: 'favicons#show'
    get 'apple-touch-icon*all', to: 'favicons#show'
    get '/sections', to: 'sections#index'
    get '/:id', to: 'sections#show', as: :s_section
    get '/:section_id/:id', to: 'images#show', as: :s_image
  end
end

app/views/layouts/_application_without_nav.html.haml
!!!5
%html{lang: (@site.language if @site) || 'en', manifest: ( cookies[:offline].present? ? '/basic.appcache' : nil ) }
  %head
    %title= title.html_safe
    - if @site.favicon?
      - [57, 114, 72, 144, 60, 120, 76, 152, 180].each do |size|
        %link{ rel: 'apple-touch-icon', sizes: "#{size}x#{size}", href: @site.favicon.url(:thumb, "thumb#{size}") }
      - [192, 160, 96, 16, 32].each do |size|
        %link{ rel: 'icon', type: 'image/png', href: @site.favicon.url(:thumb, "thumb#{size}"), sizes: "#{size}x#{size}" }
      %meta{ name: 'msapplication-TileImage', content: @site.favicon.url(:thumb, "thumb144") }
      %meta{ name: 'msapplication-TileColor', content:"#2b5797" }

    %meta{ name: 'google', content: 'notranslate' }
    %meta{ name: 'description', content: title}
    %meta{ name: 'apple-mobile-web-app-capable', content: 'yes' }
    %meta{ name: 'apple-mobile-web-app-status-bar-style', content: 'black-translucent' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0' }
    = render 'layouts/javascript_class'
    = yield(:head)
    - if @site
      - if @site.metas.present?
        =raw @site.metas
      - begin
        - if @site.css.present?
          :sass
            #{@site.css}
      - rescue Exception=> e
        /
          = e.message
    - if @section
      = stylesheet_link_tag "application-#{@section.theme}", media: 'all'
    - else
      = stylesheet_link_tag 'application', media: 'all'

    - unless @site.font_body? and @site.font_header?
      = stylesheet_link_tag "//fonts.googleapis.com/css?family=Ubuntu", media: 'all'
    - if @site.font_body?
      = stylesheet_link_tag "//fonts.googleapis.com/css?family=#{@site.font_body.sub(' ', '+')}", media: 'all'
      :sass
        body
          font-family: '#{@site.font_body}' sans-serif
    - if @site.font_header?
      = stylesheet_link_tag "//fonts.googleapis.com/css?family=#{@site.font_header.sub(' ', '+')}", media: 'all'
      :sass
        h1, h2, h3, h4, h5, h6
          font-family: '#{@site.font_header}' sans-serif
    -# if cookies[:css_loaded].present?
      - else
        %style{:'data-css' => asset_path('application.css')}
          =Rails.application.assets.find_asset('application.css').to_s.html_safe
    = csrf_meta_tags
  %body{ class: "#{body_class} #{("section-#{@section.name.parameterize} #{@section.theme}" unless @section.nil?)}" }
    = render 'layouts/cache_update'
    = yield :nav
    = yield
    - if @site && @site.google_analytics_id
      :javascript
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', '#{@site.google_analytics_id}', '#{ENV['DOMAIN']}');
        ga('send', 'pageview');
    = render 'layouts/async_js' ,path: 'application'

app/views/layouts/_async_js.html.erb
<script type="text/javascript">
  window.onload = function() {
    if(window.parent.frames.length > 0){
      return
    }
    var script = document.createElement('script');
    script.type = 'text/javascript';
    script.async = true;
    script.src = '<%= j javascript_path(path) %>';
    var other = document.getElementsByTagName('script')[0];
    other.parentNode.insertBefore(script, other);
  };
</script>

app/views/layouts/_async_js.html.haml
:coffee
  return if window.soslide
  script = document.createElement('script')
  script.type = 'text/javascript'
  script.async = true
  script.src = '#{ j(javascript_path(path)) }'
  other = document.getElementsByTagName('script')[0]
  other.parentNode.insertBefore(script, other)

app/views/layouts/_breadcrumbs.html.slim
- if user_signed_in?
  .col-md-12
    = raw breadcrumbs style: :bootstrap

app/views/layouts/_cache_update.html.slim
.cache-update
  a href = '#' = t '.new_update'

app/views/layouts/_facebook.html.haml
- if ENV['FB_PIXEL'].present? || flash[:facebook_pixel].present?
  :javascript
    (function() {
      var _fbq = window._fbq || (window._fbq = []);
      if (!_fbq.loaded) {
        var fbds = document.createElement('script');
        fbds.async = true;
        fbds.src = '//connect.facebook.net/en_US/fbds.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(fbds, s);
        _fbq.loaded = true;
      }
    })();
    window._fbq = window._fbq || [];
  - if ENV['FB_PIXEL'].present?
    :javascript
      window._fbq.push(['addPixelId', '#{ENV['FB_PIXEL']}']);
      window._fbq.push(['track', 'PixelInitialized', {}]);
    %noscript
      %img{ height: '1', width: '1', alt: '', style: 'display:none', src: "https://www.facebook.com/tr?id=#{ENV['FB_PIXEL']}&amp;ev=PixelInitialized" }

  - if flash[:facebook_pixel].present?
    :javascript
      window._fbq.push(['track', '#{flash[:facebook_pixel]}', {'value':'0.00','currency':'USD'}]);
    %noscript
      %img{ height: '1', width: '1', alt: '', style: 'display:none', src: "https://www.facebook.com/tr?ev=#{flash[:facebook_pixel]}&amp;cd[value]=0.00&amp;cd[currency]=USD&amp;noscript=1" }

app/views/layouts/_flashs.html.haml
- contexts = { success: 'success', error: 'danger', alert: 'danger', notice: 'info' }
- flash.each do |name, msg|
  .col-md-12
    - context = contexts[name.to_sym]
    - if context
      = alert_box msg, context: context

app/views/layouts/_javascript_class.html.haml
:coffee
  document.documentElement.className += ' js '

app/views/layouts/_nav.html.haml
- if site and site.sections.not_empty.count > 1
  = link_to sections_path, id: 'home' do
    .fa.fa-home
    =t('.menu', default: 'Menu')

app/views/layouts/_segment_io.html.haml
- if ENV['SEGMENT_IO'].present?
  :javascript
    window.analytics||(window.analytics=[]),window.analytics.methods=["identify","track","trackLink","trackForm","trackClick","trackSubmit","page","pageview","ab","alias","ready","group","on","once","off"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var method=window.analytics.methods[i];window.analytics[method]=window.analytics.factory(method)}window.analytics.load=function(t){var a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"d2dq2ahtl5zl1z.cloudfront.net/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)},window.analytics.SNIPPET_VERSION="2.0.8",
    window.analytics.load("#{ENV['SEGMENT_IO']}");
    window.analytics.page();

app/views/layouts/_update.html.slim
- unless browser.modern?
  .container-fluid.browser-update
    .row
      .col-xs-12
        = alert_box context: :danger do
          = link_to 'https://browser-update.org/update.html', target: '_blank' do
            = t('.update', browser: browser.name, version: browser.full_version)

app/views/layouts/_user_navbar.html.slim
nav#nav.navbar.navbar-inverse role="navigation"
  .container-fluid
    .navbar-header
      = link_to user_signed_in? ? user_path(id: current_user) : root_path, class: 'navbar-brand' do
        = t('brand')
      button.navbar-toggle data-target='#bs-example-navbar-collapse-1' data-toggle='collapse' type='button'
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        - if user_signed_in?
        - if site and not site.new_record?
          - site.sections.each do |section|
            - unless section.new_record?
              = tab_link edit_site_section_path(id: section, site_id: site) do
                = section.name
          = tab_link new_site_section_path(site_id: site) do
            .fa.fa-plus
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          = tab_link edit_user_registration_path(id: current_user) do
            = current_user.email
          li
            = link_to destroy_user_session_path, class: 'sign-out' do
              .fa.fa-sign-out
              = t 'sign_out'
        - else
          = tab_link new_user_session_path, class: 'sign-in' do
            = t 'sign_in'
          = tab_link new_user_registration_path, class: 'register' do
            = t 'register'
      - if user_signed_in?
        - if site and not site.new_record?
          = link_to preview_link, target: '_blank', title: t('.see'), class: 'pull-right btn btn-success navbar-btn' do
            = t '.see'
      - else

app/views/layouts/admin.html.haml
!!!5
%html{html_attrs(@site ? @site.language : :en)}
  %head
    %meta{:charset => "utf-8"}
    - title = "#{(@site.title if @site)} #{yield(:section_title)} #{t('.title')}".strip
    %title= title.html_safe
    %meta{ name: 'description', content: title}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
    - I18n.available_locales.each do |locale|
      %link{ rel: :alternate, href: url_for(locale: locale), hreflang: locale }
    %link{ rel: :alternate, href: url_for(locale: nil), hreflang: 'x-default' }
    = render 'layouts/javascript_class'
    = stylesheet_link_tag "//fonts.googleapis.com/css?family=Ubuntu", media: 'all'
    = stylesheet_link_tag 'admin', media: 'all'
    = javascript_include_tag 'admin'
    = csrf_meta_tags
    = render 'layouts/analytics'
    %meta{ name: 'theme-color', content: '#4cb27c' }
    %link{:href => "/apple-touch-icon-57x57.png", :rel => "apple-touch-icon", :sizes => "57x57"}/
    %link{:href => "/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/
    %link{:href => "/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    %link{:href => "/apple-touch-icon-144x144.png", :rel => "apple-touch-icon", :sizes => "144x144"}/
    %link{:href => "/apple-touch-icon-60x60.png", :rel => "apple-touch-icon", :sizes => "60x60"}/
    %link{:href => "/apple-touch-icon-120x120.png", :rel => "apple-touch-icon", :sizes => "120x120"}/
    %link{:href => "/apple-touch-icon-76x76.png", :rel => "apple-touch-icon", :sizes => "76x76"}/
    %link{:href => "/apple-touch-icon-152x152.png", :rel => "apple-touch-icon", :sizes => "152x152"}/
    %link{:href => "/apple-touch-icon-180x180.png", :rel => "apple-touch-icon", :sizes => "180x180"}/
    %meta{:content => "Evlaa", :name => "apple-mobile-web-app-title"}/
    %link{:href => "/favicon-192x192.png", :rel => "icon", :sizes => "192x192", :type => "image/png"}/
    %link{:href => "/favicon-160x160.png", :rel => "icon", :sizes => "160x160", :type => "image/png"}/
    %link{:href => "/favicon-96x96.png", :rel => "icon", :sizes => "96x96", :type => "image/png"}/
    %link{:href => "/favicon-16x16.png", :rel => "icon", :sizes => "16x16", :type => "image/png"}/
    %link{:href => "/favicon-32x32.png", :rel => "icon", :sizes => "32x32", :type => "image/png"}/
    %meta{:content => "#2d89ef", :name => "msapplication-TileColor"}/
    %meta{:content => "/mstile-144x144.png", :name => "msapplication-TileImage"}/
    %meta{:content => "Evlaa", :name => "application-name"}/
  %body{ class: body_class }
    = render 'layouts/update'
    = render 'layouts/user_navbar', site: @site, section: @section, image: @image
    = render 'layouts/breadcrumbs'
    = render 'layouts/flashs'
    = yield
  - if current_user
    = intercom_script_tag({ user_id: Digest::SHA1.hexdigest("#{ENV['DOMAIN']}-#{current_user.email}"),
                            email: current_user.email,
                            created_at: current_user.created_at,
                            custom_data: {sections: Section.count, images: Image.count, site: ENV['DOMAIN']}})

app/views/layouts/application.html.haml
= render layout: 'layouts/application_without_nav' do
  .row
    = yield